version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx/
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wrd:/var/www/html
    networks:
      - my_network
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb/
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - dba:/var/lib/mysql/
    networks:
      - my_network
    restart: always
      
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wrd:/var/www/html
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge
    
volumes:
  dba:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/abel-bou/data/mariadb
  wrd:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/abel-bou/data/wordpress
