version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: requirements/mariadb/
    env_file:
      - .env
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - my_network
      
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress/
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - my_network
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx/
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: on-failure

networks:
  my_network:
    driver: bridge
volumes:
  mariadb:
      driver_opts:
        type: 'none'
        o: 'bind'
        device: /Users/abel-bou/data/mariadb
  wordpress:
      driver_opts:
        type: 'none'
        o: 'bind'
        device: /Users/abel-bou/data/wordpress
